# Generated by Django 5.1.6 on 2025-02-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_healthgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthGoal',
        ),
    ]
